### ISSUE TITLE
Create organization avatar

### ISSUE THREAD

**Issue by twolfson** [gmusic-utils/meta#1]
Now that we have a GitHub organization, it's in need of an avatar for our brand. I suggest we start with something simple and can't get trademark infringement on. Here's a bunch of options from [Noun Project](https://thenounproject.com/):

Eighth music note: https://thenounproject.com/search/?q=music&i=111

Pair of eighths: https://thenounproject.com/search/?q=music&i=113110

More for music search: https://thenounproject.com/search/?q=music

Speaker: https://thenounproject.com/search/?q=speakers&i=100

For those that haven't used the Noun Project before, we can use the icon for free based on the licensing terms (usually CC 3.0 which requires Attribution).

**Comment by MarshallOfSound** [comment]
Are we avoiding a GMusic headphone icon for trademark safety or could we use something like this?

https://thenounproject.com/search/?q=headphones&i=12188

**Comment by twolfson** [comment]
We could use headphones. We actually do this on `google-music-electron` which I think is why I was trying to avoid similar logos:

https://github.com/twolfson/google-music-electron/blob/2.5.0/lib/assets/icon-32.png

**Comment by chrismou** [comment]
Threw this together in photoshop using the existing logo as a base.  Got that sort of familiar, but different vibe about it :wink: 

![google-play-music-logo-32](https://cloud.githubusercontent.com/assets/319883/11918759/b5039c36-a736-11e5-8070-17641f742c47.png)

![google-play-music-logo-64](https://cloud.githubusercontent.com/assets/319883/11918763/b7baf3fc-a736-11e5-9c85-6e1e4804a32b.png)

![google-play-music-logo](https://cloud.githubusercontent.com/assets/319883/11918758/af221fcc-a736-11e5-89cc-5400b8d73551.png)

**Comment by twolfson** [comment]
imo it looks way too similar to Google Music's logo. What are our thoughts on combining headphones with some sort of tool icon (e.g. toolbox, wrench, screwdriver, gear)?

**Comment by twolfson** [comment]
Here's an example of headphones in a gear:

![headphones-in-gear](https://cloud.githubusercontent.com/assets/902488/11919275/9eb339dc-a713-11e5-9e8b-2e75a1920509.png)

![headphones-in-gear-64](https://cloud.githubusercontent.com/assets/902488/11919274/9eb1f694-a713-11e5-8139-8a9219abb4b4.png)

![headphones-in-gear-32](https://cloud.githubusercontent.com/assets/902488/11919273/9eb08a8e-a713-11e5-83ac-360abbd70882.png)

**Comment by twolfson** [comment]
Attribution for icons:

Headphones by Molly Bramlet from the Noun Project

https://thenounproject.com/search/?q=headphones&i=16961

Gear by Tarah from the Noun Project

https://thenounproject.com/search/?q=gear&i=10651

**Comment by chrismou** [comment]
That looks OK, except I can imagine it spray painted onto walls.  It reminds me of some sort of 70's revolutionary activist group's logo.

Might look better with a bit of colour

![noun_25088_cc](https://cloud.githubusercontent.com/assets/319883/11926510/6c11c94e-a7bd-11e5-9a65-14c38fbd85d4.png)

Or maybe even the whole thing orange.

![noun_25088_cc_o](https://cloud.githubusercontent.com/assets/319883/11926606/09c01bfa-a7be-11e5-83ea-fa21c66044f8.png)

TBH the cog is a bit too thick too - I grabbed a smaller one from that site, but that's a bit thick too. Might look better if it was a bit more low key. I'll have another look next time I'm in front of the laptop.

**Comment by twolfson** [comment]
Yea, I agree about the cogs being too thick. I tried tweaking the SVG but my looked awkward (e.g. the circle deformed improperly).

As a heads up, I went with the 6 point cog since Google uses a 6 point one as well (doubt there is trademark issues there):

![selection_203](https://cloud.githubusercontent.com/assets/902488/11926970/8c7bbdc2-a78e-11e5-9bc2-148c73008d62.png)

I feel like we should have the logo consistently colored but feel like the orange might be overpowering =/

Here's a contextual preview of each of our designs (always something good to consider in design):

![selection_205](https://cloud.githubusercontent.com/assets/902488/11927023/fea92cea-a78e-11e5-85c6-32e8ca29c3f5.png)

![selection_206](https://cloud.githubusercontent.com/assets/902488/11927025/01706d62-a78f-11e5-9370-161daa7d41b7.png)

**Comment by chrismou** [comment]
Yeah. seeing it on the page I'm not sure. The black one looks good, but then purely by coincidence the orange one looks cool with the tab highlight below it ;-)

How about the first one but in #333 to match Github's text colour?  Might just make it look a little less out of place

**Comment by twolfson** [comment]
Let's try it out, want to mock it up?

**Comment by chrismou** [comment]
Just looking now!

Are you sure that cog you linked to (https://thenounproject.com/search/?q=gear&i=10651) is the one you used? It looks a load thicker in photoshop. Might just be an illusion though

**Comment by twolfson** [comment]
Oh, yea -- I tweaked the SVG circle. I dragged out the points until they started deforming to not be a circle. Feel free to play around with that.

Another thing to try might be to grab a wire-y gear and remove the center circle:

https://thenounproject.com/search/?q=gear&i=102547

**Comment by chrismou** [comment]
![400](https://cloud.githubusercontent.com/assets/319883/11940157/b9231876-a81e-11e5-8a56-2504ee8c4957.jpg) ![128](https://cloud.githubusercontent.com/assets/319883/11940158/b9239f6c-a81e-11e5-98c9-6f327eba9600.jpg) ![64](https://cloud.githubusercontent.com/assets/319883/11940156/b922a120-a81e-11e5-9293-5bdcb139ec92.jpg)

**Comment by chrismou** [comment]
Other possibilities:

![2 - 256](https://cloud.githubusercontent.com/assets/319883/11940386/3a86209c-a820-11e5-9f0a-6423014a7ba5.jpg) ![3 - 256](https://cloud.githubusercontent.com/assets/319883/11940388/3a8718bc-a820-11e5-8738-58884c1432f1.jpg)

**Comment by twolfson** [comment]
Oh, damn. Both of those look great (hollow and headphone cut-out). Nice touch on the off-grey :+1:

**Comment by chrismou** [comment]
Couple of other sizes to get an idea of what it looks like scaled

![2 - 128](https://cloud.githubusercontent.com/assets/319883/11941798/1501ff62-a82a-11e5-898d-713737df3c1d.jpg) ![2 -64jpg](https://cloud.githubusercontent.com/assets/319883/11941799/1513fee2-a82a-11e5-9d88-427acf834e50.jpg)

@gmusic-utils/gmusic-js What do you guys reckon? Preferences? Or any other ideas?

Edit - looks like I've messed up that graphic a bit. Must have been where I made it square. Ah well, if we like it I'll go back and do it properly

**Comment by jacobwgillespie** [comment]
My favorite so far is the one you just sent (the headphone cut out of the gear)

**Comment by twolfson** [comment]
:+1: for the cutout. I think next steps would be to add the source file and an SVG to this repo (e.g. `assets` folder) or an `assets` repo. Want to open up a PR with that?

**Comment by twolfson** [comment]
Also, please be sure to add attribution to a README or the source logo itself (or let's purchase the icons).

**Comment by chrismou** [comment]
Yep, no worries. I'll tidy up the PSD, export some SVGs and PNGs and put in a PR

I may just buy them. Not even £3 for both. Well worth the money IMO. Will stick an attribution on in the meantime

**Comment by twolfson** [comment]
:+1: :+1: :tada:

**Comment by twolfson** [comment]
This has been completed by @chrismou in #2 =D
