### ISSUE TITLE
GMusic theming library

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/meta#3]
Hey guys,

I just got round to cleaning up (kinda) and pushing my theming JS.  Interested to hear what you guys think of it.  Follows a different core style than GMusic.js but ends up with a similiar kinda of usage.

https://github.com/MarshallOfSound/gmusic-theme.js

Thoughts on whether this should be moved into this org?

/cc @gmusic-utils/meta

**Comment by twolfson** [comment]
The gist of everything looks good, although I see lots of room for improvement. I'm pretty sure we can move it into the organization.

**Comment by chrismou** [comment]
:+1: 

As mentioned in that other discussion thread, it may be worth having a discussion on how to better group the selectors, and what other groups might be worth having (buttons, etc).  But aside from that, it looks good. Looking forward to getting it implemented in radiant :smile:

**Comment by MarshallOfSound** [comment]
@twolfson Yeah, it could still do with some tidying
@chrismou The grouping of selectors is definitely something to look at, originally they were kinda logically grouped, but then I was just adding them as they were needed.

**Comment by twolfson** [comment]
Alright, looks like it's been moved. Closing this issue =)
