### ISSUE TITLE
Add @jostrander as gmusic-utils member

### ISSUE THREAD

**Issue by twolfson** [gmusic-utils/meta#4]
Hey @gmusic-utils/gmusic-js, @jostrander has been submitting a lot of good PRs to `gmusic.js` (i.e. gmusic-utils/gmusic.js#39, gmusic-utils/gmusic.js#40, gmusic-utils/gmusic.js#41). I want to add them as a member to the group. Any thoughts?

/cc @gmusic-utils/gmusic-js

**Comment by jostrander** [comment]
:+1: I'm game, but I'm also biased..

**Comment by jacobwgillespie** [comment]
:+1: from me!

**Comment by MarshallOfSound** [comment]
**GMuisc Utils Checklist**
- [x] Fixed an issue when no one else would
- [x] Has spent at least an hour puzzling over the test suite
- [x] Has realized that adding a test can make 6 others fail

:+1:  from me :laughing:

**Comment by twolfson** [comment]
Alright, adding to the group and to `npm` :tada:

**Comment by twolfson** [comment]
@jostrander Can you verify this is your `npm` handle? https://www.npmjs.com/~jostrander

**Comment by jostrander** [comment]
That is indeed me

**Comment by twolfson** [comment]
Cool, you have been added to `gmusic.js` on `npm`. I will leave it to @MarshallOfSound to add you to `gmusic-theme.js` since it's their repo more than mine
